name: Compile Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run compile
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/saladbind-win.exe
            bin/saladbind-macos
            bin/saladbind-linux
