name: VirusTotal Scan

on:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_KEY }}
          update_release_body: true
          github_token: ${{ secrets.BEEPBOOP_TOKEN }}
          files: |
            saladbind-(linux|macos|win.exe)
